[agent]
  metric_batch_size = 5000
  metric_buffer_limit = 100000
  interval = "1s"
  round_interval = true
  flush_interval = "5s"
  omit_hostname = true
  debug = false

[[inputs.mqtt_consumer]]
  name_override = "mqtt_measurement"
  servers = ["tcp://mosquitto:1883"]
  topics = ["C-S/+/+/+/+/+/+/+"]
  data_format = "json"
  json_string_fields = ["*"]

  [[inputs.mqtt_consumer.topic_parsing]]
    topic = "C-S/+/+/+/+/+/+/+"
    tags = "_/_/_/_/line_code/equip_name/station/_"

[[inputs.mqtt_consumer]]
  name_override = "mqtt_status"
  servers = ["tcp://mosquitto:1883"]
  topics = ["C-S/+/+/+/+/+/+/+/status"]
  qos = 1
  data_format = "json_v2"

  [[inputs.mqtt_consumer.json_v2]]
    measurement_name = "mqtt_status"

    [[inputs.mqtt_consumer.json_v2.object]]
      path = "sensors"
      disable_prepend_keys = true
      included_keys = [
        "sensor_code",
        "conn_status",
        "last_seen",
        "health_score",
        "error_msg",
        "update_time",
      ]

      [inputs.mqtt_consumer.json_v2.object.fields]
        sensor_code = "string"
        conn_status = "string"
        last_seen = "string"
        health_score = "float"
        error_msg = "string"
        update_time = "string"

  [[inputs.mqtt_consumer.topic_parsing]]
    topic = "C-S/+/+/+/+/+/+/+/status"
    tags = "_/_/_/_/line_code/equip_name/station/source/status_suffix"

[[processors.execd]]
  namepass = ["mqtt_measurement"]
  command = ["python3", "-u", "/telegraf/telegraf_py/measurement_processor.py"]
  restart_delay = "10s"

[[processors.execd]]
  namepass = ["mqtt_status"]
  command = ["python3", "-u", "/telegraf/telegraf_py/status_processor.py"]
  restart_delay = "10s"

[[outputs.postgresql]]
  namepass = ["measurement"]
  connection = "postgres://admin:1q2w3e4r@hmi-db-postgres:5432/edge_hmi?sslmode=disable"
  schema = "core"
  name_override = "measurement"
  tagexclude = ["host", "line_code", "equip_code", "equip_name", "station", "topic"]

[[outputs.sql]]
  namepass = ["sensor_status"]
  driver = "pgx"
  data_source_name = "postgres://admin:1q2w3e4r@hmi-db-postgres:5432/edge_hmi?sslmode=disable&search_path=core"
  name_override = "sensor_status"
  timestamp_column = "update_time"
